### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by cschafferGRCC**

### CODE REVIEW

**Review by joshfornerschool — CHANGES_REQUESTED** [review]
The shopping list should exist on the user object, just like the current UserList does. No need to make whole new classes for it

**Comment by cschafferGRCC** [comment]
Alicia thought it was a good idea. But okay.

**Comment by joshfornerschool** [comment]
Unless you are planning on letting a user have more than one shopping list, there isn't much need

**Comment by cschafferGRCC** [comment]
Well, it does tell us the user must be able to save the shopping list, so
it's a possibility we may have to handle

**Comment by joshfornerschool** [comment]
I'm pretty sure the save part of that means to save it somewhere like the database and be able to retrieve it later

**Comment by AliciaRogers** [comment]
The more I think about it, I'm not sure that a class makes sense here. I'm thinking that it would be better to create a deque with the book objects in the user or userDatabase classes, like we did for the print list functions. Maybe, by default, we create a table in the database with a name like shoppingCart-username so the shopping cart can be saved and retrieved.

**Comment by cschafferGRCC** [comment]
Sounds good

**Pull request closed without merging**
